services:
  hexafunds.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=tototata 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=https/aspnetapp.pfx
    ports:
      - 80
      - 443
    volumes:
      - ~/.aspnet/https:/https:ro